/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { SourceService } from "../source.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { SourceCreateInput } from "./SourceCreateInput";
import { Source } from "./Source";
import { SourceFindManyArgs } from "./SourceFindManyArgs";
import { SourceWhereUniqueInput } from "./SourceWhereUniqueInput";
import { SourceUpdateInput } from "./SourceUpdateInput";
import { DataRecordFindManyArgs } from "../../dataRecord/base/DataRecordFindManyArgs";
import { DataRecord } from "../../dataRecord/base/DataRecord";
import { DataRecordWhereUniqueInput } from "../../dataRecord/base/DataRecordWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class SourceControllerBase {
  constructor(
    protected readonly service: SourceService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Source })
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createSource(@common.Body() data: SourceCreateInput): Promise<Source> {
    return await this.service.createSource({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        role: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Source] })
  @ApiNestedQuery(SourceFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async sources(@common.Req() request: Request): Promise<Source[]> {
    const args = plainToClass(SourceFindManyArgs, request.query);
    return this.service.sources({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        role: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async source(
    @common.Param() params: SourceWhereUniqueInput
  ): Promise<Source | null> {
    const result = await this.service.source({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        role: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateSource(
    @common.Param() params: SourceWhereUniqueInput,
    @common.Body() data: SourceUpdateInput
  ): Promise<Source | null> {
    try {
      return await this.service.updateSource({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          role: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Source })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteSource(
    @common.Param() params: SourceWhereUniqueInput
  ): Promise<Source | null> {
    try {
      return await this.service.deleteSource({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          role: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/dataRecords")
  @ApiNestedQuery(DataRecordFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "read",
    possession: "any",
  })
  async findDataRecords(
    @common.Req() request: Request,
    @common.Param() params: SourceWhereUniqueInput
  ): Promise<DataRecord[]> {
    const query = plainToClass(DataRecordFindManyArgs, request.query);
    const results = await this.service.findDataRecords(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        smKey: true,
        dateTime: true,
        oilName: true,
        oilLongName: true,
        literPrice: true,
        literLast: true,
        amountDeliv: true,
        typeField: true,
        literDeliv: true,
        amountLast: true,

        source: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dataRecords")
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "update",
    possession: "any",
  })
  async connectDataRecords(
    @common.Param() params: SourceWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        connect: body,
      },
    };
    await this.service.updateSource({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dataRecords")
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "update",
    possession: "any",
  })
  async updateDataRecords(
    @common.Param() params: SourceWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        set: body,
      },
    };
    await this.service.updateSource({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dataRecords")
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "update",
    possession: "any",
  })
  async disconnectDataRecords(
    @common.Param() params: SourceWhereUniqueInput,
    @common.Body() body: DataRecordWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dataRecords: {
        disconnect: body,
      },
    };
    await this.service.updateSource({
      where: params,
      data,
      select: { id: true },
    });
  }
}
