/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { DataRecord } from "./DataRecord";
import { DataRecordCountArgs } from "./DataRecordCountArgs";
import { DataRecordFindManyArgs } from "./DataRecordFindManyArgs";
import { DataRecordFindUniqueArgs } from "./DataRecordFindUniqueArgs";
import { CreateDataRecordArgs } from "./CreateDataRecordArgs";
import { UpdateDataRecordArgs } from "./UpdateDataRecordArgs";
import { DeleteDataRecordArgs } from "./DeleteDataRecordArgs";
import { Source } from "../../source/base/Source";
import { DataRecordService } from "../dataRecord.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => DataRecord)
export class DataRecordResolverBase {
  constructor(
    protected readonly service: DataRecordService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "read",
    possession: "any",
  })
  async _dataRecordsMeta(
    @graphql.Args() args: DataRecordCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [DataRecord])
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "read",
    possession: "any",
  })
  async dataRecords(
    @graphql.Args() args: DataRecordFindManyArgs
  ): Promise<DataRecord[]> {
    return this.service.dataRecords(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => DataRecord, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "read",
    possession: "own",
  })
  async dataRecord(
    @graphql.Args() args: DataRecordFindUniqueArgs
  ): Promise<DataRecord | null> {
    const result = await this.service.dataRecord(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DataRecord)
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "create",
    possession: "any",
  })
  async createDataRecord(
    @graphql.Args() args: CreateDataRecordArgs
  ): Promise<DataRecord> {
    return await this.service.createDataRecord({
      ...args,
      data: {
        ...args.data,

        source: args.data.source
          ? {
              connect: args.data.source,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => DataRecord)
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "update",
    possession: "any",
  })
  async updateDataRecord(
    @graphql.Args() args: UpdateDataRecordArgs
  ): Promise<DataRecord | null> {
    try {
      return await this.service.updateDataRecord({
        ...args,
        data: {
          ...args.data,

          source: args.data.source
            ? {
                connect: args.data.source,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => DataRecord)
  @nestAccessControl.UseRoles({
    resource: "DataRecord",
    action: "delete",
    possession: "any",
  })
  async deleteDataRecord(
    @graphql.Args() args: DeleteDataRecordArgs
  ): Promise<DataRecord | null> {
    try {
      return await this.service.deleteDataRecord(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Source, {
    nullable: true,
    name: "source",
  })
  @nestAccessControl.UseRoles({
    resource: "Source",
    action: "read",
    possession: "any",
  })
  async getSource(
    @graphql.Parent() parent: DataRecord
  ): Promise<Source | null> {
    const result = await this.service.getSource(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
